// 全部 UI 文案集中在此。Yuqing 体验后直接改这里，不要散落到各模块。
// 结构预留 i18n：将来只需把 copy 换成 copy[lang]。

export const copy = {
  start: {
    title: '笑一下，屏幕会开花',
    subtitle: '微笑会下雨，大笑会放烟花。',
    button: '开始',
    needCamera: '需要打开摄像头',
    liveDemo: 'Live Demo · 画面只在本机处理，不会上传',
    // 按钮自己变状态，没有独立错误页——用户永远停在这一页
    stageCamera: '正在打开摄像头',
    stageModel: '正在准备',
    modelLine: '正在加载识别模型',
    stageWarmup: '正在启动识别',
    noCamera: '摄像头未开启，直接开始',
    retryCamera: '重试摄像头',
    previewAlt: '玩法封面',
  },
  guide: {
    step1: '对着镜头微笑，雨就会落下来',
    step2: '再张开嘴大笑试试',
    step3: '摆摆头，让烟花撞到你',
    done: '玩法解锁了，尽情笑吧',
    smileBar: '微笑',
    laughBar: '大笑',
  },
  hud: {
    manualHint: '点一下下雨 · 长按放烟花',
    manualRelease: '松手放烟花',
    gear: '设置',
    exit: '退出',
    hideUi: '隐藏界面',
    showUi: '显示界面',
    share: '分享截图',
    shareTitle: '笑雨烟花',
    shared: '已分享',
    downloaded: '截图已保存',
    shareFail: '截图没成功，再试一次',
  },
  manual: {
    // 手动模式必须自己说出来自己是手动模式，否则用户会以为是识别坏了
    banner: '手动模式',
    reconnect: '重连摄像头',
    connecting: '正在连接…',
  },
  status: {
    noFace: '把脸放进画面里',
    lowLight: '光线有点暗，换个亮一点的地方',
    paused: '已暂停，回到页面后自动继续',
    idleTitle: '一直没看到人，已经暂停了',
    idleHint: '点一下继续',
  },
  error: {
    denied: '没有拿到摄像头权限',
    timeout: '摄像头一直没有响应，可能被其它程序占用',
    unsupported: '这个浏览器不支持摄像头',
    modelFail: '识别模型没有加载成功，检查网络后重试',
    deniedSteps: {
      iosSafari: '点地址栏左边的「ᴀA」→ 网站设置 → 摄像头 → 允许',
      iosOther: '点地址栏左边的站点图标 → 权限 → 摄像头 → 允许',
      androidChrome: '点地址栏左边的锁 → 权限 → 摄像头 → 允许',
      desktopChrome: '点地址栏右边被划掉的摄像头图标 → 始终允许',
      desktopSafari: 'Safari 浏览器 → 设置 → 网站 → 摄像头 → 允许',
      desktopFirefox: '点地址栏左边被划掉的摄像头图标 → 清除阻止',
      generic: '在浏览器站点设置里把摄像头改成「允许」',
    },
  },
  drawer: {
    title: '设置',
    advancedTitle: '触发阈值',
    advancedHint: '给运营 / 设计调参用，改完不用重新部署',
    smileThreshold: '微笑阈值',
    laughThreshold: '大笑阈值',
    rainMax: '雨量上限',
    fireworkCount: '烟花粒子数',
    burstScale: '烟花范围',
    restitution: '碰撞弹性',
    hueShift: '色调偏移',
    showGuide: '显示提示与进度条',
    showDebug: '显示调试数据',
    showCollider: '显示碰撞体',
    personSeg: '人像遮挡与碰撞（低档机自动关）',
    advancedLink: '触发阈值与特效参数',
    replayGuide: '重看新手引导',
    copyConfig: '复制配置给开发',
    copied: '已复制到剪贴板',
    close: '关闭',
  },
} as const
